recipe_path: /home/ericdill/dev/conda-forge/feedstocks/feedstocks/petsc4py/recipeTraceback (most recent call last):
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/environ.py", line 703, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 811, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 850, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 376, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda/resolve.py", line 302, in verify_specs
    raise NoPackagesFoundError(bad_deps)
conda.exceptions.NoPackagesFoundError: Package missing in current linux-64 channels: 
  - tbb 2017.*_20170604 hd56f8c0.*_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build-feedstocks.py", line 39, in build
    api.build(recipe_path)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1622, in build_tree
    test(pkg, config=metadata.config)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1406, in test
    channel_urls=tuple(metadata.config.channel_urls))
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/environ.py", line 705, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['tbb']
