recipe_path: /home/ericdill/dev/conda-forge/feedstocks/feedstocks/pygmo_plugins_nonfree/recipeTraceback (most recent call last):
  File "build-feedstocks.py", line 39, in build
    api.build(recipe_path)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 966, in build
    try_download(m, no_download_source=False)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/render.py", line 356, in try_download
    source.provide(metadata)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/source.py", line 594, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/source.py", line 107, in unpack
    src_path = download_to_cache(cache_folder, recipe_path, source_dict)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/source.py", line 85, in download_to_cache
    (tp.upper(), hashed, expected_hash))
RuntimeError: SHA256 mismatch: '0805afa8af939da284855848b5f1df3d4c80c4ded55940bc27942a946c202c13' != '66a6793598653f33fb331e8ed2e9e582fcf44b3bfb23229ebd81bb892542bb6a'
