recipe_path: /home/ericdill/dev/conda-forge/feedstocks/feedstocks/xarray-simlab/recipeTraceback (most recent call last):
  File "build-feedstocks.py", line 39, in build
    api.build(recipe_path)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 183, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1615, in build_tree
    built_packages=built_packages,
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 966, in build
    try_download(m, no_download_source=False)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/render.py", line 356, in try_download
    source.provide(metadata)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/source.py", line 594, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/source.py", line 107, in unpack
    src_path = download_to_cache(cache_folder, recipe_path, source_dict)
  File "/home/ericdill/miniconda/lib/python3.6/site-packages/conda_build/source.py", line 85, in download_to_cache
    (tp.upper(), hashed, expected_hash))
RuntimeError: SHA256 mismatch: '13213be316f62c7f627a3ba1b37cbcdb7f0a7aacb851d34f3f5944d6dbc050c6' != '1aa4617421521f757c8de418f11bb861b376cd23dfa6b8e934185d51ded4d6cb'
